# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Naren Viswanath
user_description: Developer | Solution Specialist | Philanthropist | Fintech Enthusiast | Hiring 
user_title: Software Developer
email: naren.viswanath@outlook.com
twitter_username: narenviswa
github_username:  detroitFive
gplus_username:  narenviswa

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
